// <auto-generated />
using System;
using AssetTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ef_core_asset_tracking.Migrations
{
    [DbContext(typeof(AssetTrackerDbContext))]
    [Migration("20240112131019_MoreAssets")]
    partial class MoreAssets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("AssetTracker.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("TEXT");

                    b.Property<int>("Location")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Siemens",
                            DateOfPurchase = new DateTime(2021, 1, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = 0,
                            Model = "WS100",
                            Price = 2500,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Asus",
                            DateOfPurchase = new DateTime(2023, 11, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = 0,
                            Model = "Zenbook",
                            Price = 745,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Nokia",
                            DateOfPurchase = new DateTime(2021, 4, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = 0,
                            Model = "4.2",
                            Price = 180,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Xiaomi",
                            DateOfPurchase = new DateTime(2020, 9, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = 2,
                            Model = "Redmi 5",
                            Price = 320,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Brand = "LG",
                            DateOfPurchase = new DateTime(2022, 2, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = 2,
                            Model = "Max",
                            Price = 545,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Vivo",
                            DateOfPurchase = new DateTime(2021, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = 2,
                            Model = "V-10Micro",
                            Price = 125,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Samsung",
                            DateOfPurchase = new DateTime(2021, 5, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = 1,
                            Model = "Pad 5",
                            Price = 855,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Asus",
                            DateOfPurchase = new DateTime(2022, 8, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = 1,
                            Model = "Matepad",
                            Price = 395,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Huawei",
                            DateOfPurchase = new DateTime(2023, 6, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = 1,
                            Model = "Ultra",
                            Price = 680,
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
