// <auto-generated />
using System;
using AssetTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ef_core_asset_tracking.Migrations
{
    [DbContext(typeof(AssetTrackerDbContext))]
    [Migration("20240111111330_FinalizeDatabase")]
    partial class FinalizeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("AssetTracker.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("TEXT");

                    b.Property<int>("Location")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Siemens",
                            DateOfPurchase = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 0,
                            Model = "WS100",
                            Price = 2500,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Nokia",
                            DateOfPurchase = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 2,
                            Model = "6.1",
                            Price = 500,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Samsung",
                            DateOfPurchase = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = 1,
                            Model = "ST-14",
                            Price = 400,
                            Type = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
